### ISSUE TITLE
Size mismatch when loading us_mobilenet_v1_calibrated.pt

### ISSUE THREAD

**Issue by bermanmaxim** [JiahuiYu/slimmable_networks#24]
When launching `python train.py app:apps/us_mobilenet_v1_train_val.yml` with `logs/us_mobilenet_v1_calibrated.pt` downloaded, I get size mismatch errors for all the `running_mean` and `running_var` of batchnorm; should I delete these parameters from the checkpoint and relaunch calibration before testing?

**Comment by JiahuiYu** [comment]
@bermanmaxim Sorry I missed a flag in the code. You are right - you can delete these parameters from the checkpoint and our code will relaunch calibration. The model I released is with some BN statistics of multiple widths.

I have fixed this problem in a new commit and please try out. Thanks for your interest in our work.

**Comment by DamonAtSjtu** [comment]
When I set  ‘’width_mult_list_test‘’ with some other values that I want to test, I still meet the size mismatch errors for  all the  running_mean and running_var of batchnorm; I think this is because logs/us_mobilenet_v1_calibrated.pt has the bn parameters of all the width in "width_mult_list". You said you fix this problem, I want to know which version should I use to avoid this problem?
